inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

# Put development dependencies in the gemspec so rubygems.org knows about them
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Make BeginEndAlignment behavior match EndAlignment
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

# Be lenient with line length
Layout/LineLength:
  Max: 92

# Don't force lonely closing parentheses
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Force consistent spacing independent of block contents
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

# Use standardrb style hash literals
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Assume the programmer knows precendence rules
Lint/AmbiguousOperatorPrecedence:
  Enabled: false

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Performance/StartWith:
  AutoCorrect: true

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# Use standardrb style empty methods
Style/EmptyMethod:
  EnforcedStyle: expanded

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Make quoting outside and inside interpolation consistent
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

# Accessors are only trivial if they match the ivar name
Style/TrivialAccessors:
  ExactNameMatch: true
